apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-crds
  namespace: kube-system
spec:
  chart: traefik-crds
  repo: https://helm.traefik.io/traefik
  version: 1.10.0

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  targetNamespace: traefik
  version: 37.0.0
  valuesContent: |-
    ingressClass:
      enabled: true
      isDefaultClass: true

    # To maintaint Traefik v2 compatibility
    # https://doc.traefik.io/traefik/v3.0/migration/v2-to-v3/#new-v3-syntax-notable-changes
    core:
      defaultRuleSyntax: v2

    logs:
      general:
        level: INFO
      access:
        enabled: true
        format: json

    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: "public-ips"

    ports:
      websecure:
        forwardedHeaders:
          insecure: true

    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
