apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        - name: external-dns
          env:
            - name: EXTERNAL_DNS_PIHOLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sec-pihole
                  key: WEBPASSWORD
            - name: EXTERNAL_DNS_PIHOLE_SERVER
              value: http://svc-pihole-internal.pihole.svc.cluster.local
          args:
            - --source=service
            - --source=ingress
            # Pihole only supports A/CNAME records so there is no mechanism to track ownership.
            # You don't need to set this flag, but if you leave it unset, you will receive warning
            # logs when ExternalDNS attempts to create TXT records.
            - --registry=noop
            # IMPORTANT: If you have records that you manage manually in Pi-hole, set
            # the policy to upsert-only so they do not get deleted.
            - --policy=upsert-only
            - --provider=pihole
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files
