apiVersion: batch/v1
kind: CronJob
metadata:
  name: photoprism-index
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: photoprism
              image: photoprism
              workingDir: "/photoprism"
              envFrom:
                - configMapRef:
                    name: cm-app-photoprism
                - secretRef:
                    name: sec-app-photoprism
              # Don't use args since photoprism's entrypoint script keeps on retrying
              # https://github.com/photoprism/photoprism/commit/8bfd95ddc4d198bafdc1a6eb1bba352bff4500be
              command:
                - photoprism
                - index
              resources:
                requests:
                  cpu: 1000m
                  memory: 1Gi
                limits:
                  cpu: 2000m
                  memory: 3Gi
              volumeMounts:
                - mountPath: /photoprism/originals/Shivansh
                  name: data-originals
                  subPath: Shivansh
                - mountPath: /photoprism/storage
                  name: data-photoprism
                  subPath: storage
          volumes:
            - name: data-originals
              hostPath:
                path: /mnt/storage
            - name: data-photoprism
              hostPath:
                path: /mnt/data1/photoprism
