apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana
  namespace: kube-system
spec:
  chart: grafana
  repo: https://grafana.github.io/helm-charts
  targetNamespace: monitoring
  version: 6.43.3
  valuesContent: |-
    ingress:
      enabled: true
      hosts: [ "pi.shivanshs9.me" ]
      path: "/grafana"
      tls:
        - hosts:
            - pi.shivanshs9.me
          secretName: tls-pi-shivanshs9-me
    grafana.ini:
      server:
        root_url: https://pi.shivanshs9.me/grafana
        serve_from_sub_path: true

    persistence:
      type: pvc
      enabled: true
      size: 4Gi

    envFromSecret: sec-influxdb

    # ref: http://docs.grafana.org/administration/provisioning/#dashboards
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'general'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: true
          updateIntervalSeconds: 10
          allowUiUpdates: true
          options:
            path: /var/lib/grafana/dashboards/general
        - name: 'k8s'
          orgId: 1
          folder: 'Kubernetes'
          type: file
          disableDeletion: true
          updateIntervalSeconds: 10
          allowUiUpdates: true
          options:
            path: /var/lib/grafana/dashboards/k8s

    dashboardsConfigMaps:
      general: grafana-folder-general
      k8s: grafana-folder-k8s

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: InfluxDB
            uid: P951FEA4DE68E13C5
            type: influxdb
            access: proxy
            url: $INFLUXDB_URL
            secureJsonData:
              token: $INFLUXDB_TOKEN
            jsonData:
              version: Flux
              organization: "IIT BHU"
              defaultBucket: "TheFaker"
          - name: InfluxDB-SQL
            uid: v2zmXou4z
            type: influxdb
            access: proxy
            url: $INFLUXDB_URL
            database: TheFaker
            secureJsonData:
              httpHeaderValue1: 'Token $INFLUXDB_TOKEN'
            jsonData:
              dbName: TheFaker
              httpMode: GET
              httpHeaderName1: 'Authorization'
