apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yml
  - telegraf-chart.yml
  - telegraf-rbac.yml
  - grafana-chart.yml
  - dashboards

generators:
  - generator.yml

labels:
  - pairs:
      app.kubernetes.io/component: tick
      app.kubernetes.io/part-of: monitoring
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/created-by: controller-manager
    includeSelectors: true
  - pairs:
      app.kubernetes.io/version: latest # TODO: add support of dynamic versioning in label
    includeSelectors: false
