apiVersion: v1
kind: Secret
metadata:
    name: sec-influxdb
type: Opaque
data:
    INFLUXDB_TOKEN: ENC[AES256_GCM,data:KJScvf/dGvEUQjgLh1QQkqoALuzdzpNn5wPAd5GaZFkXmnZQNqb1DJTYuucrRDSxkd+dsc4ingWJ7ZLr6FBuZ70SM9iF9kuwfOi8x50t2EQdR9CV6eK7EdIW+R0nntXrLeiuEZtRpbDM61/kYY4KbZW7HHDacvAg,iv:r5+1K8/nVkH/iOoaLN3VoGEnubSnB7i8ajMDsBycL9E=,tag:KCuuw++bLt/+JwLK0l2otQ==,type:str]
    INFLUXDB_URL: ENC[AES256_GCM,data:X12sgxZyPYJlZHsoYisAW/Uf+e7DYo1ZGJm5Te32+d26oUVNvrAU0y4plaVmC+0P6wwr+4lEOwiOjcPv8HsfOAcKEv4=,iv:LCsA7ogQXc4RnSM4XWCuei8/4PsR3uPt5jkHpxl+ONA=,tag:JiDZo1aftHDvgrlqFrkPLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986unduzas5d7r3aytfyj3ye55x4l6d8f9fly29j6g9slddu39qqfz6ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSGpvekF5VmFEYWZqcUlF
            NGl0UDRnS3A0bGlRbk9JZGlzbjFZS2xVUkVFCndUcjh5eUhsN2RFUFRaa2l1M1M1
            TmE4TGVqZWlONUlrMm5OS0E1N2pNb28KLS0tIGt0ZXpabEZiZlNxdXZFdFJCb3cv
            MURMa1N5WHBwQTZHWVEyUzBFaU41ZkUKLOD3XaMktOEG9xX5u8xM4Te/izvRO3ng
            yAEFVH13Sv9dpNbDUihsC+CUI6k7K+RPm7yxgGxz7C+i0NG2RZM7jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-20T15:15:20Z"
    mac: ENC[AES256_GCM,data:x7pXDA6t1QVdVkTUD2xTAw5xf7zomCaS2eXPjTNAfHrl5aqlAmrDpW/utrQPxHrxcPw/Yme5B9Sj4vXF5ZrlEc42SffoVEdse4b7oixGbwNGavdzLSy73/Kj2ilvCbW5AcQIM5JgjlcbECgUUy2fK7n+ST9pr7H5OPjyAfIH0AI=,iv:ARQ8a9UfN1otssIzoEMm8ZRZxSkJFT7SJZR5lgDMO6w=,tag:VDm8wmkMVD9GmFm8sLQXwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
