version: '3.8'

services:
  dashy:
    image: lissy93/dashy:arm64v8
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

