apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yml
  - service.yml
  - config.yml
  - cron-snapshot.yml

generators:
  - generator.yml

labels:
  - pairs:
      app.kubernetes.io/name: db-mariadb
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: photoprism
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/created-by: controller-manager
    includeSelectors: true
  - pairs:
      app.kubernetes.io/version: latest # TODO: add support of dynamic versioning in label
    includeSelectors: false
