apiVersion: v1
kind: Secret
metadata:
    name: sec-db-mariadb
type: Opaque
data:
    MARIADB_PASSWORD: ENC[AES256_GCM,data:WDN5iMHXT/H3HKNA+OuZzQ==,iv:RXexA/We0n+78aDElkzrptP/7YTiPjrHc5sgft0CaOE=,tag:U8oMfSUhB9iIApuvMWWuHA==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:4yqirkhWbiBmcPYyXdgSIg==,iv:zHGJN1WlcJkt3iYP92H3thuCgadb1sfcpvlwISRAHfs=,tag:rK71GZcVvv87NISzdrAgVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9rc4u588qjh8num2u6yth5mlagk5p97y9n69p4a4smsgqk7jvjsef90ta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaU5jaFlLVTc5SXRkeTlq
            cFA1YjdqTjk2ajFUWGJnQzRrVXJ0RjJFMlZFCmZmdUFuUXJrTWJxL2pmUjBPSVVL
            QWtheUoyZFZONFloVTNSYjc3dVI0WmMKLS0tIElhcXNGUnI2Mk9CUTNkNktaY2wz
            aUF1LzhXTTNJSUpRR1hGamJ5NndyUVkK0/BkNhubLk4AI8B8GtlEHT7tIrjRlspN
            52ke0SCd+yDPm/vtdR0FYS7LB6Ih+ji9V7dJduLli1QnhISBGNkqpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-24T14:46:24Z"
    mac: ENC[AES256_GCM,data:4DCQsP3b3v75kc1esc6J1FLLJHC90GqElm0R6Q087MvORVdqkhBSEqNxEuppFW8TeOChrDATNtxz/5Qbz0IiNKvX4uqlDKBZqJ8jlpvlph8q8YwqfC+WXt59y4l5OERz4XHFrEqSfx7OIcy+qTuBJs8r90Z4ImLIIZipQXHWjsY=,iv:EfFdDPbiGQLNXFM0rH9zrBs7IFykKCIfB8kJhXXgy+g=,tag:P3nhvKjmO9Q9aI8/gbD5iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
