apiVersion: apps/v1
kind: Deployment
metadata:
  name: pidrive
spec:
  replicas: 1
  template:
    spec:
      initContainers:
        - name: init-configs
          image: busybox
          command: ["sh", "-c", "cp /cm-configs/* /cfg"]
          volumeMounts:
            - name: configs
              mountPath: /cfg
            - name: cm-configs
              mountPath: /cm-configs
      containers:
        - name: copyparty
          image: ghcr.io/9001/copyparty-ac:1.18.10
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Asia/Tokyo"
          ports:
            - containerPort: 3923
              protocol: TCP
              name: http
          volumeMounts:
            - name: configs
              mountPath: /cfg
            - name: nas-pidrive
              mountPath: /w/pidrive
          resources:
            requests:
              memory: 128Mi
              cpu: 150m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /?reset=/._
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
      volumes:
        - name: cm-configs
          configMap:
            name: cm-copyparty
        - name: nas-pidrive
          hostPath:
            path: /mnt/pidrive
            type: Directory
        - name: configs
          emptyDir: {}
