apiVersion: v1
kind: Secret
metadata:
    name: sec-app-photoprism
type: Opaque
data:
    PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:R27N92KEQBxMCYcn,iv:7OVgV3rGakG+hpy24zHezaiiOgKd20HTvSb1lOzgN1Q=,tag:t8bh0IPZGaCP4OX329LVmg==,type:str]
    PHOTOPRISM_DATABASE_PASSWORD: ENC[AES256_GCM,data:i1pIgBg8D81uD2H+lcHNSA==,iv:RYwqW9kuiVBB/Bn87AEEe50cmkfZjOM3mgc1pzG3+GI=,tag:V5LGd4vkKnYzHPGNNf8eGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986unduzas5d7r3aytfyj3ye55x4l6d8f9fly29j6g9slddu39qqfz6ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcE1FcTR5Uk9zeThoQVI0
            MjdvVEl2UUdXeHJtOFdHMEJlaVljMUdBaVhnClhyZlA2aWdkMnpOamNMSG44Mk8z
            ZVNJTXRkTEF5Y2lzQ2pmRkxXU2ZuUE0KLS0tIE5tcGRFSnZJWWpsdFZNNGpsSXgz
            VXBUTWhMRmMybmpXZDVuSEpEVG5ESlkKZbDUu7ZgVTkBg95IAfnRMiMBrgfi4Cgz
            OxBZ7VyPVkUUY/8c/eB8VYRRMqeKfrPLW3mgyTOdoTgZtC8JiJrglg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-29T21:02:40Z"
    mac: ENC[AES256_GCM,data:/nN8Kw07LSYHDR9mqFLSLhkJBLi06g2hM9coGfThHqaDJ9zMKDncMqRk4NmkzjT6CzRBUMHrJWad/AtqzBOnCuumDr9VnJpdvJzJmmhljMMEcGggGrIlG9fs2GuFPkeQD58Uj3yoNGlx0Ryb88e9Jen0+MkGLy/r5Yl8YADJXl4=,iv:dG0Yj9VnezdTtmRwqQ9S2+bjnRRd5oN5qWMnz/l+b3c=,tag:pO66foKdGirdlaGH0dHK8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
