kind: Service
apiVersion: v1
metadata:
  name: svc-photos-internal
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 2342
      name: http

---

apiVersion: v1
kind: Service
metadata:
  name: photos
  annotations:
    metallb.universe.tf/address-pool: "mesh-ips"
    external-dns.alpha.kubernetes.io/hostname: "photos.pi."
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
