apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio-web
spec:
  template:
    spec:
      containers:
        - name: stremio-web
          image: registry.pi/shivanshs9/stremio-web:6d92e038
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
            requests:
              memory: "64Mi"
              cpu: "20m"
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
