apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

labels:
  - pairs:
      app.kubernetes.io/name: web-stremio
      app.kubernetes.io/component: web
      app.kubernetes.io/part-of: stremio
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/created-by: controller-manager
    includeSelectors: true
  - pairs:
      app.kubernetes.io/version: latest # TODO: add support of dynamic versioning in label
    includeSelectors: false
