apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  - https://github.com/metallb/metallb//config/frr?ref=v0.14.9
  - metallb-private-ippool.yml
  - metallb-mesh-ippool.yml

patches:
  - path: patch-frr-speaker.yaml
