apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private-ips
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.3 - 192.168.1.7

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: private-layer2
  namespace: metallb-system
