apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-ips
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.69/32
    - 2401:4900:1c31:47f1:56f8:5d0b:682a:270c/128

---
kind: L2Advertisement
metadata:
  name: lb-layer2
  namespace: metallb-system
