apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speaker
spec:
  template:
    spec:
      containers:
        - name: reloader
          command: ["sh", "/etc/frr_reloader/frr-reloader.sh"]
        - name: frr-metrics
          command: ["bash", "-c"]
          # Copying to /home since we get Permission Denied (idk why :/)
          args:
            - "cp /etc/frr_metrics/frr-metrics /home/frr-metrics && /home/frr-metrics -metrics-port=7473"
