apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  # External DNS
  - external-dns

generators:
  - generator.yml

labels:
  - pairs:
      app.kubernetes.io/name: pihole
      app.kubernetes.io/component: system
      app.kubernetes.io/part-of: pihole
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/created-by: controller-manager
    includeSelectors: true
  - pairs:
      app.kubernetes.io/version: latest # TODO: add support of dynamic versioning in label
    includeSelectors: false
