apiVersion: v1
kind: Service
metadata:
  name: svc-pihole
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.69"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
