apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 1
  template:
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          # upstream DNS used by pihole.
          - 1.1.1.1
      containers:
        - name: pihole
          image: pihole/pihole:2023.05.2
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Asia/Kolkata"
            - name: FTLCONF_LOCAL_IPV4
              value: "0.0.0.0"
            - name: PIHOLE_DNS_
              value: "1.1.1.1"
            - name: MAXDBDAYS
              value: "7"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  key: WEBPASSWORD
                  name: sec-pihole
          securityContext:
            privileged: true
          ports:
            - containerPort: 53
              protocol: TCP
              name: dns
            - containerPort: 53
              protocol: UDP
              name: dns-udp
            - containerPort: 67
              protocol: UDP
              name: dhcp
            - containerPort: 80
              protocol: TCP
              name: http
            - containerPort: 443
              protocol: TCP
              name: https
          volumeMounts:
            - name: etc
              mountPath: /etc/pihole
            - name: dnsmasq
              mountPath: /etc/dnsmasq.d
            - mountPath: /dev/shm
              name: dshm
          resources:
            requests:
              memory: 128Mi
              cpu: 150m
            limits:
              memory: 512Mi
              cpu: 500m
      volumes:
        - name: etc
          hostPath:
            path: /etc/pihole
            type: Directory
        - name: dnsmasq
          hostPath:
            path: /etc/dnsmasq.d
            type: Directory
        - name: dshm
          emptyDir:
            medium: Memory
