kind: Service
apiVersion: v1
metadata:
  name: svc-pihole-internal
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      name: http

---
apiVersion: v1
kind: Service
metadata:
  name: svc-pihole
  annotations:
    metallb.universe.tf/address-pool: "private-ips"
    external-dns.alpha.kubernetes.io/hostname: "pi.hole."
spec:
  type: LoadBalancer
  # Set Local externalTrafficPolicy is equivalent to IP
  # target type in AWS LB; traffic to a node is sent to node-local
  # endpoint instead of being routed between the nodes.
  ## Client IP is preserved.
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns-udp
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dns
