apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - namespace.yaml

generators:
  - generator.yaml

helmCharts:
  - name: immich
    releaseName: onepiece
    version: 1.0.0
    valuesFile: values.yaml

helmGlobals:
  chartHome: ../helm-charts
