apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: auth-zitadel
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.shivanshs9.me`)
      kind: Rule
      services:
        - name: zitadel
          port: http2-server
  tls:
    secretName: tls-pi-shivanshs9-me
