apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - namespace.yaml
  - ingress.yaml

generators:
  - generator.yml

helmCharts:
  - name: zitadel
    releaseName: zitadel
    repo: https://charts.zitadel.com
    version: 8.4.1
    valuesFile: values.yaml
