apiVersion: v1
kind: Secret
metadata:
    name: sec-zitadel
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:kiMepW5635kysJbLxMeaOuasMca3yaRMQ0BSZpKuluE=,iv:WWm8tpRSLdRUTIKlNXHFRJb3rUBFm7mqx4ITBcSJQV0=,tag:HrM01CUCzVoz6fXUut1PzA==,type:str]
    config-yaml: ENC[AES256_GCM,data:DqLdxn2APCYlYJQ8Lbi8msXD80BTkntnZVgl/2ocfes9T6x6bjAGlu3v7K59j0J8jOb9SUAOQmvpHRUTnGXtEwysSaD1k+4IXSV3i6X3wHFMTaknS++a289tSD0LiLhv9SUZ82WP,iv:dnfy59kLUXjpvdOltJep/ArOnzBzAiUaT18i93aEqqo=,tag:frMn4isJf1wcDkW8xOlzKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9rc4u588qjh8num2u6yth5mlagk5p97y9n69p4a4smsgqk7jvjsef90ta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSDE4VmU3N1pHM0wyWFZS
            NnJxQk1rQTlPK3h4Ky95d08wdUNvTjc0V2dnCmtSeWlCbzhvK3hYd3ZNMG9uMXJ1
            dlRZOXVSL29weVRNMytQbFR3MEh0OUEKLS0tIG1SbDRsZmRwbnNRbUoxc3psOVhL
            bW14bzlkdDArYTN2WkRDb1g5aC9ROEEKSTaZCLLDRwdqRfzg9Kfl6Bca2Y4z4VZX
            ud74Iho1VENtQbTDQRER4aTOkiu5iw15vq+d00NUSiNHp8IQ7+hqnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-19T08:00:05Z"
    mac: ENC[AES256_GCM,data:OqDpiIfutmbMpv1Pia1fAO5xNeuougHC27o7Mi2dRpZAjRAMjNSWDMt3M6B+0AD4h/2sd4MLiiKoXpoDRaLIyrXtMDi7FcJUQjSYpXr3HewW4ICU/TVgh4bxNvIQwfkbuIEv67Lct297i/IaOKIoHG1pcRnV7vbNKGjZtfTKe6A=,iv:yW4H9QviGmMlMZRGLcOF+cvpFd7fmcIipqaw/z7bP0U=,tag:TECsz60MyN2oWez3Mgkvaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
