apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  targetNamespace: traefik
  version: 18.1.0
  valuesContent: |-
    ingressClass:
      enabled: true
      isDefaultClass: true

    logs:
      general:
        level: INFO
      access:
        enabled: true

    service:
      enabled: true
      type: LoadBalancer
      # annotations:
      #   metallb.universe.tf/loadBalancerIPs: ""
      spec:
        ipFamilyPolicy: RequireDualStack

    ports:
      websecure:
        forwardedHeaders:
          insecure: true
