apiVersion: v1
kind: Namespace
metadata:
  name: reflector

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: reflector
  namespace: kube-system
spec:
  chart: reflector
  targetNamespace: reflector
  repo: https://emberstack.github.io/helm-charts
