apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - deployment.yml
  - service.yml
  - ingress.yml

labels:
  - pairs:
      app.kubernetes.io/component: registry
      app.kubernetes.io/part-of: docker-registry
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/created-by: controller-manager
    includeSelectors: true
  - pairs:
      app.kubernetes.io/version: latest # TODO: add support of dynamic versioning in label
    includeSelectors: false
