apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio-server
spec:
  template:
    spec:
      containers:
        - name: stremio-server
          image: shivanshs9/stremio-streaming-server:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
              cpu: "4M"
            requests:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: FIX_UNSUPPORTED_MEDIA
              value: "1"
          ports:
            - containerPort: 11470
          volumeMounts:
            - mountPath: /root/.stremio-server/
              name: cache-stremio
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      volumes:
        - name: cache-stremio
          hostPath:
            path: /mnt/data1/stremio
