apiVersion: v1
kind: Secret
metadata:
    name: sec-db-postgres
type: Opaque
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:idiQ7IlI3eXV1Uzi0dPUxQ==,iv:l7hTX2aaKu8fDDxmLkEWAmChohSevmLCQH4pMmNITVo=,tag:0QF5wH0FXdFA9zxrCOZ9bg==,type:str]
    POSTGRES_MULTIPLE_DATABASES: ENC[AES256_GCM,data:ODDIYjWsUQkQn0L3aMwwaCqZ92kiuBOrMjyh5RV5hoAluiT7XtrRZ1fVFJcnd/r7/mEcGoETO0VQ76fsk48dkKPJYQCtmU1AyBpsDQ==,iv:VbI63fUzVcsWeeTQLFLphFbb6hzrZ/yFm9x+iCQPluE=,tag:oJtyyb8dj4AzayNi5bxfug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986unduzas5d7r3aytfyj3ye55x4l6d8f9fly29j6g9slddu39qqfz6ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQ0Z4ZVl2RzRlUUpMMTI3
            bi91RzYxUmJxZkg4VmlGTExscjN4VUhvcDFnClBkb29xS2laTjNuRTJ0QldmdUo5
            TWNtWEdRZmlTK1A3U2hPaWVKWFlxMUkKLS0tIDNDckhGNytOcW9WeFJKK2JTYzNN
            MzR3U1l4cWN0M29GeTBIeXM3cU1RUDQKgXu8y2GA9oCC4lT/1P/rD8qUczx/TNDY
            cc74kKBG+zQIHeT9zt7k/+uLV+YWm+rNbSUM4j27fARKEzp6mWu+og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-26T19:36:45Z"
    mac: ENC[AES256_GCM,data:ZGQtwFIpX6VWkBYa/VBV6SN7E1Jx0k3Z1ia1NFQ7/IXdmAufFs+lgGCh+WLiXSDhWw4s7GQUa9Fe2Rj6Zt0HrSgP7n9UdG05BxzgIklpO0FPLkAJOO7nk+fAJS7tenYn0zmgagbX1GLSZ6aYR7ha05pE1Z2nG/D7o8hovd11fsA=,iv:obZWMWkNpnH8+UTDldbzQrS4tkJRlQ880yfLAFlsEpA=,tag:RiVkX8btxljWKkfLRr1h5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
