apiVersion: v1
kind: Secret
metadata:
    name: sec-db-postgres
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1rlYmxprVtInZ6SVv8/jeQ==,iv:+qMfe+MSsRYvHjal/gTua5SaLNFXLMv1B3vrgP606g4=,tag:MP0kIfoSbJyNimHGiGwohw==,type:str]
    POSTGRES_MULTIPLE_DATABASES: ENC[AES256_GCM,data:ptkzWx+M//ACCkhhnbTNH/OZFY0KQ2MYEdfluHdmPiPtxT9Z5kGAC11vu8yaesh6GCaPD30qa21uZKeZi0oUxHghC2kII2QNuVDaDP7oKo8CIdLOkg==,iv:K7PDSP6xtREzcLAk9GPHO9G5HV3nFjeYD+y2sZT/4ro=,tag:5q1cScO3Z9eLpktbAXGqaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986unduzas5d7r3aytfyj3ye55x4l6d8f9fly29j6g9slddu39qqfz6ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZXp4cnFsWHNEb2o1NXNX
            cW1UQWZVeFQvT0RvaUVnYzgvN0RwQXdNTDFJCjhUU0I5OGNoWjlqRFprZkpwOHBr
            cXQ3Z1czV0Zxa0dlTTI1b1AvWGRYc2sKLS0tIDNZUTZwYzB2cXpKeENTcTZVVVBJ
            UHFOWWxMMk4zS0FWSVNIUXlDUzlDSmsK6TmL6uV+eQMvhh/H7e4/gqi1UNwU08ii
            HyYeMtYjZvuPbFyt4NAF/KR309R0eDkdkk3cJNvtiOCZoELETOxgKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-09T18:48:16Z"
    mac: ENC[AES256_GCM,data:RIjLT/SELYCfwywIG7CNu3P2w5tY8+5ezDV0KQkFZ8AVtCLDwI47M1/9oRufzV2OXeaDfFXdlAslTmQ7QAW9eja1f862YehPIIJ56VkEZpJwQTRv23QRD7E2jgvDV4KUDX+wvxKMYUW+QhTYf+NUrNh1GjuEZdq784F3g08knqQ=,iv:4f80tYRYRdBYT7WV9QrwxQJGM3H/OXOikodZdgwZiGk=,tag:ZnzFYsyAWW+oiu6mqr9vyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
