apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-postgres
spec:
  serviceName: svc-db-postgres
  template:
    spec:
      containers:
        - name: app
          image: arm64v8/postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
          envFrom:
            - secretRef:
                name: sec-db-postgres
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-db-postgres
            - mountPath: /docker-entrypoint-initdb.d/create-multi-db.sh
              name: sh-create-multi-db
              subPath: create-multi-db.sh
      volumes:
        - name: data-db-postgres
          hostPath:
            path: /mnt/data1/k8s/db-postgres
        - name: sh-create-multi-db
          configMap:
            name: sh-postgres-create-multi-db
            defaultMode: 0744
