apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-retain
allowedTopologies: []
mountOptions: []
parameters: {}
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
