apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden-server
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vault.shivanshs9.me`)
      kind: Rule
      services:
        - name: vaultwarden-server
          port: http
  tls:
    secretName: tls-pi-shivanshs9-me
