apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - namespace.yaml
  - ingress.yaml

generators:
  - generator.yml

helmCharts:
  - name: vaultwarden
    releaseName: vaultwarden
    repo: http://guerzon.github.io/vaultwarden/
    version: 0.32.4
    valuesFile: values.yaml

# patches:
#   - target:
#       kind: Deployment
#       name: vaultwarden-server
#     patch: |-
#       - op: replace
#         path: /spec/template/spec/containers/0/ports/0/containerPort
#         value: 8080