apiVersion: v1
kind: Secret
metadata:
    name: sec-vault
type: Opaque
stringData:
    postgres_uri: ENC[AES256_GCM,data:ZKTTk+QMsJDXZ1fdM0WLhnBkwwyLigRyfXnIR5f8JrKSDn1vyDHfouLr6oSw3k7McbVYJnQG48VGWIX+sh2ktN1v3WGafQZdWFh9oeBa5YMCZusd22WyNFab,iv:lM1xtydm41uYWsfUtut7ly8M20/GtdG4fSi05vRCa6g=,tag:VltWjcPvOhQ1wyOjT0rB2Q==,type:str]
    smtp_username: ENC[AES256_GCM,data:LIk9vPRM,iv:Tajtb/LGAO7ZriEt5Djf/W84tINzKlJIGTsc6ou76pM=,tag:y+tLqVgls4nP6uI+yz+3Pw==,type:str]
    sendgrid_key: ENC[AES256_GCM,data:QOaI1DEBh5/Yil5CTAOHz4HllpECTJpJqsWo5R4YrTYnumkZGiWHurWqclUtm8P6U9EO/8tS5VwRqN126LdP3w8kuUk3,iv:6kN13cx0nTtKBLcytzUb2rWnGjambKY1tra8VfUxXOg=,tag:NaAxesCGaeQ1WtF/znRD7Q==,type:str]
    admin_token: ENC[AES256_GCM,data:09YZcwOfGGORwSm4+qitUVXXmjgfUjFvDpmDy0hVqSBky2zazLwCaYgCb+yNetu0OzVg616hMaui2Vo41V7kMrqaJzBM+m+Av+oPW68qe5jMagMNXJcBbcP+g5bOqbPUvosaBZVDbGXNyvVSBuZfmRJw9XTwCA==,iv:E3JogCzMz5S1B5Lj5rke71OkSLJ+A/j/8QuOSna0F8E=,tag:fyXniW+EH2z9FMqBcXk7RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986unduzas5d7r3aytfyj3ye55x4l6d8f9fly29j6g9slddu39qqfz6ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZUhnTk1YaXNIMnNPSnJs
            dnZxRGk1Y1Z5WDR1Q05LR2RKWmxsbWJ5eFRvCnVPNHBTU2xqYmxlTGJqVDNlaWxv
            QkZHNG56OHYwTTgwOEVOd3NkRDQybVkKLS0tIEFBYjU3ZzI1RnVTUERnZG1Majhn
            S2Eya0IvSmtqUENDdlVwUWtiZFEyRU0KXrR5ERi7ITsTM9AKnlZ/+1XPDjHfs1ZD
            kqG6p9gjq2nUZZjVjDJCk0iXLfvUI/y6v89c9kYLjCMt0uHo9IuALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-25T20:55:04Z"
    mac: ENC[AES256_GCM,data:bT5b40rQLIDdS7Igr4weVMa+O8Idn8nSJhQPeSOWDZh9tGP1wcGvRc3rTXUzosiyQo1oy/CQeh0dHFaBdnAtDf/j/RWgjB4NHhOYGiqNF2LDtGhHRG+MyabgxAJ/U4t5jbubzFV7TTeMEdnfonY5n1hRfMwySfgOuwq5Qgp1FPA=,iv:hrg0QLlYotDIpuIX3ql54ffPCy8U4Wd21IT4yi3uIv0=,tag:dScNsp/j9Son2SAO4jSYvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
