nameOverride: server

image:
  repository: vaultwarden/server
  tag: 1.34.3-alpine

replicas: 1

service:
  port: 8080
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

domain: https://vault.shivanshs9.me

adminToken:
  existingSecret: sec-vault
  existingSecretKey: admin_token

pushNotifications:
  enabled: true
  existingSecret: sec-vault
  installationId:
    existingSecretKey: installation_id
  installationKey:
    existingSecretKey: installation_key

database:
  type: postgresql
  existingSecret: "sec-vault"
  existingSecretKey: "postgres_uri"

smtp:
  existingSecret: sec-vault
  host: smtp.sendgrid.net
  port: 587
  from: no-reply@shivanshs9.me
  fromName: "Vault Admin"
  username:
    existingSecretKey: smtp_username
  password:
    existingSecretKey: sendgrid_key
  authMechanism: "Login"

signupsAllowed: true
signupDomains: shivanshs9.me

domain: https://vault.shivanshs9.me

resources:
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 100Mi

ingress:
  enabled: false

storage:
  enabled: true
  data:
    name: data
    size: "1Gi"
    class: "local-path-retain"
    accessMode: "ReadWriteOnce"
    keepPvc: "true"
  attachments:
    name: attachments
    size: "1Gi"
    class: "local-path-retain"
    accessMode: "ReadWriteOnce"
    keepPvc: "true"
