apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/external-dns/kustomize

patches:
  - path: deployment.yml

labels:
  - pairs:
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/component: system
      app.kubernetes.io/part-of: external-dns
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/created-by: controller-manager
    includeSelectors: true
  - pairs:
      app.kubernetes.io/version: latest # TODO: add support of dynamic versioning in label
    includeSelectors: false
