apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - snapshot.yml

labels:
  - pairs:
      app.kubernetes.io/component: cronjobs
    includeSelectors: true

configMapGenerator:
  - files:
      - sh-backup-db.sh
    name: sh-postgres-backup-multi-db