apiVersion: v1
kind: Namespace
metadata:
  name: ory

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ory-kratos
  namespace: kube-system
spec:
  chart: kratos
  repo: https://k8s.ory.sh/helm/charts
  targetNamespace: ory
  version: 0.26.2
  valuesContent: |-
    ingress:
      admin:
        enabled: true
        hosts:
          - host: "auth.shivanshs9.me"
            paths:
              - path: "/"
                pathType: Prefix
        tls:
          - hosts:
              - auth.shivanshs9.me
            secretName: tls-pi-shivanshs9-me

    secret:
        enabled: false

    kratos:
      config:
        identity:
          default_schema_id: default
          schemas:
            - id: default
              url: file:///etc/config/identity.default.schema.json
        courier:
          smtp:
            connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
        selfservice:
          default_browser_return_url: http://127.0.0.1:4455/
      automigration:
        enabled: true
      identitySchemas:
        "identity.default.schema.json": |
          {
            "$id": "https://schemas.ory.sh/presets/kratos/identity.username.schema.json",
            "title": "Person",
            "type": "object",
            "properties": {
              "traits": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string",
                    "title": "Username",
                    "maxLength": 100,
                    "ory.sh/kratos": {
                      "credentials": {
                        "password": {
                          "identifier": true
                        },
                        "webauthn": {
                          "identifier": true
                        },
                        "totp": {
                          "account_name": true
                        }
                      }
                    }
                  }
                },
                "required": [
                  "username"
                ],
                "additionalProperties": false
              }
            }
          }
