apiVersion: v1
kind: Secret
metadata:
    name: ory-kratos
    namespace: ory
type: Opaque
data:
    dsn: ENC[AES256_GCM,data:CcHPhmOXtnajgOqijB7yOsum+XQKlkDZhEkMpyM+gI4U+7UMv2niBCg+0EkoLPxqalBnUOYvkrC1i1Ot7Nn961ppYSyTD6vi/g9NUWevqNlWyCpuiAKzbuYrFKw=,iv:ENVpGMQ07vmz+AhXlSTRBNUxdVti9aC/gnq6uLbjNIQ=,tag:mb3s1PZdE6AobgwdtwKRxQ==,type:str]
    secretsDefault: ENC[AES256_GCM,data:e5jqA5oUMhllAZlZSmlKBF27Zwfn82Om6o4mOg8aSE+AJSVFvZAwW3WJkeArUhB2hu+s1EwE/0h7ijiWytCNMUUzenThF206sz/0SM072/I7zUB9,iv:Ul30EKXWyF8NEnXaevNEC5Rs2dFtt2WR+Hud/mtzbMg=,tag:RvEh3K3BrPl7Kt3cQ5M0Wg==,type:str]
    smtpConnectionURI: ENC[AES256_GCM,data:71FFd5aExOyYWZVPj+FGMBq0QnRuiFicW0A6N2To0uL3uk9tveVYWuGV0mD7Z0k7q757hFjCwc4eUsA5HWOTTljRbcm3fFzlq7AIoQ==,iv:x2EWBf3IzNSUuW3F2WDqSECe+anRqaAKbZ3qwc/56Mk=,tag:lmDTFycrSNLsQ/lmWMNEkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9rc4u588qjh8num2u6yth5mlagk5p97y9n69p4a4smsgqk7jvjsef90ta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTU5zOGtNckZDRlYwbG5K
            RExKbmNiYTlYUUJ4RVExLzFDSEsrTTNhNWhNCkxhRGpNQWJNblJGYm1taFZ2ODdh
            UnZqK29CeXZzaW1qbnBNMkpqOGVLK3cKLS0tIHhkUFRQUm1QT2ZqK3BHbm41RTRa
            UFFhMW9nZWVVd3gwYXE4aFNmeHRzK0EKFk+OUcmAkcQBzvJNiuss+0U1J3eihx17
            0Ydx9UR/geK0MDh8JZvgtMuL1H1B1sZMqKiU5KgxhYRQuOB21xmAvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-24T14:50:02Z"
    mac: ENC[AES256_GCM,data:RNshXvZhAKF4+o2NAHFxiyjdyWkkHsYRxU6kfpCG7taTYnx/7kUs7GvoCxBLfWJtte1L/8INYiJLR7vU0d7dMlIrgQqom/lKA3/6PiHHVR7XmVLDvPPVLKZ3fWmw/AgCW8q88IGEso/CeZEAptG1DfJUioT0qIQFByO+ygzLOKM=,iv:osYGlHuVvNhIxyaLR37Tw6m5OgWLk5ThXL8TN5pEifo=,tag:vgLvZzWNShyZHXOhzzj6Mw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
