apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-journal-exchange
spec:
  replicas: 1
  template:
    spec:
      initContainers:
      - name: symlink-files
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -eux;
          apk add jq
          for dir in $(cat /app/filesData.json | jq -r '.[] | .name'); do
            cat /app/filesData.json | jq -r --arg dir "$dir" '.[] | select(.name == $dir) | .files[] | .path' | while IFS= read -r file; do
              mkdir -p $(dirname "/app/shared/$file")
              cp "/app/host/$file" "/app/shared/$file"
            done
          done
        volumeMounts:
        - name: data-host-notes
          mountPath: /app/host
          readOnly: true
        - name: data-shared-notes
          mountPath: /app/shared
        - name: cm-exchange-files
          mountPath: /app/filesData.json
          subPath: filesData.json
      containers:
        - name: app
          image: journal
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 81
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: data-shared-notes
              mountPath: /usr/share/nginx/html/data
            - name: cm-exchange-files
              mountPath: /usr/share/nginx/html/data/filesData.json
              subPath: filesData.json
              readOnly: true
            - name: cm-nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
            - name: sec-user-htpasswd
              mountPath: /etc/nginx/.htpasswd
              subPath: htpasswd
              readOnly: true
      volumes:
        - name: data-shared-notes
          emptyDir: {}
        - name: data-host-notes
          hostPath:
            path: /home/pi/Sync/Notes
            type: Directory
        - name: cm-exchange-files
          configMap:
            name: cm-exchange-files
        - name: cm-nginx-conf
          configMap:
            name: cm-nginx-conf
        - name: sec-user-htpasswd
          secret:
            secretName: sec-user-htpasswd
