apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: journal

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml

configMapGenerator:
  - name: cm-exchange-files
    files:
      - "files.json=filesData.json"

images:
  - name: journal
    newName: journal-web
    newTag: "3a41a50"
