apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yml
  - service.yml

configMapGenerator:
  - files:
      - create-multi-db.sh
    name: sh-postgres-create-multi-db

generators:
  - generator.yml

labels:
  - pairs:
      app.kubernetes.io/name: db-postgres
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: photoprism # TODO: Remove later
    includeSelectors: true
