apiVersion: v1
kind: Secret
metadata:
    name: sec-db-postgres
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:LF6LHKHjcx3Z1HkCvc6/MQ==,iv:HDr5920/+Fj+OhR/Ih+DnlxeZBf3h0DuAdKudbDKHEs=,tag:eSTPyQW6HI3kz0BSwvUvnQ==,type:str]
    POSTGRES_MULTIPLE_DATABASES: ENC[AES256_GCM,data:lKUjJgYCQvxe9iRmRdji2y1QqnWPMXLdnb52X3smaJsJUrR9CZMgxVKhETPXgcUwGq/lI2BhxdOMFglCBFl4roXn/pnJl1CsSswZ4URDx5KeUDNDwTFjbb4EqlCWe/waCOeNW1Qqd7idc2tc6MuSjp+rxw==,iv:b7rkkAw+wHRmIP6eMFNIxuPzET6qWDqVu27zGILrcRM=,tag:6LP87uX4VK95lOaeq2K7XA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9rc4u588qjh8num2u6yth5mlagk5p97y9n69p4a4smsgqk7jvjsef90ta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbTNmcngvTTlSV2FrZXU4
            enpUTkVncUpVS2dRNXJxVUJROThlWGRUcFNNCmtjUnR1b1FoY0wyZ284L2J2czQ5
            Y0w4ODI0bUN4TXY5ZVQ4dlFkSDBDeFUKLS0tIDVSNkluOERIUUJDNnFUQU9GSWVP
            TjM1SFN1dEhndjB3cFZOcmUxZnNsUTQKdyhwqZC0n0dpDUgdeFfNsUSNACBkD1cZ
            Oj4ZYMrL5wY7Bf4ymeXhPWI1xCorLuxVOpSMgPkuK4OdT7ow5ko01g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-24T14:51:04Z"
    mac: ENC[AES256_GCM,data:Oz/gs3jjdxCwIqMX/Zaq/jGVsctWJS9SiKhLEeux1vkMjIG+sPcd2kjVx5jlKm+mj/jVLKzbUamtm1wnelL5Gp4a4eCUHY0vF3AzWt+1kMLl88NqUGiS67SLgox6mApL+sFodlu8i2S8735x7CaSt0MW3a6R0YPm10FQ5nlzknw=,iv:GwYyim4Nsz3/za8+P+5Iyxomk17jCYHbiLWYy4/1rk4=,tag:cn3OBa5+OEH/Ypv2ZNtCNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
