apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-postgres
spec:
  serviceName: svc-db-postgres
  template:
    spec:
      containers:
        - name: app
          # Using https://hub.docker.com/r/tensorchord/pgvecto-rs
          # for vector similarity search in postgresql
          image: tensorchord/pgvecto-rs:pg15-v0.3.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
          envFrom:
            - secretRef:
                name: sec-db-postgres
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 300m
              memory: 1Gi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-db-postgres
            - mountPath: /docker-entrypoint-initdb.d/create-multi-db.sh
              name: sh-create-multi-db
              subPath: create-multi-db.sh
      volumes:
        - name: sh-create-multi-db
          configMap:
            name: sh-postgres-create-multi-db
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: data-db-postgres
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
        volumeMode: Filesystem
        storageClassName: local-path-retain
