apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

generators:
  - generator.yaml

namePrefix: whisper-notes-

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: grpc-backend
    app.kubernetes.io/created-by: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whisper-notes-grpc
    app.kubernetes.io/part-of: whisper-notes
- pairs:
    app.kubernetes.io/version: latest

images:
- name: grpc-backend
  newName: shivanshs9/whisper-notes-api
  newTag: 1c75ebc
