apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-ips
  namespace: metallb-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: traefik
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  addresses:
    - 192.168.1.69/32
    - $IPv6_CIDR
