apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . tls://1.1.1.1 tls://1.0.0.1 tls://2606:4700:4700::1111 {
          # the server name will be used in the TLS negotiation.
          tls_servername cloudflare-dns.com

          # the duration for checking the health of the upstream DNS server
          health_check 60s
        }
        cache 30
        loop
        reload
        loadbalance
    }
    import /etc/coredns/custom/*.server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  pi.server: |
    pi:53 {
      log
      kubernetes {
        pods disabled
      }
    }
