apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

generators:
  - generator.yml

commonAnnotations:
  reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitoring,ory,photoprism,stremio"
  reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
