apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: public-photos
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`photos.shivanshs9.me`)
      kind: Rule
      services:
        - name: svc-photos-internal
          port: http
  tls:
    secretName: tls-pi-shivanshs9-me
