apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-photos
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
spec:
  rules:
  - host: photos.pi
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: svc-app-photoprism
            port:
              name: http

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: public-photos
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`photos.shivanshs9.me`)
      kind: Rule
      services:
        - name: svc-app-photoprism
          port: http
  tls:
    secretName: tls-pi-shivanshs9-me
