apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: photoprism

resources:
  - namespace.yml
  - mariadb
  - app
  - cron
  - ingress.yml

images:
  - name: photoprism
    newName: photoprism/photoprism
    newTag: "231128"
